### ISSUE TITLE
Strange, rapid switching between selected notes in a web browser.

### ISSUE THREAD

**Issue by aerych** [Automattic/Simplenote-United#65] opened 2019-11-12 16:34 UTC
We have a report, including video examples, where the currently selected note rapidly cycles through multiple notes.  This is reproduced in multiple browsers by the user, but we haven't been able to reproduce ourselves when testing. 
For more context and examples in Safari and Chrome see: 2475811-zen

### Expected
Selecting a note should maintain the selection

### Observed
Note selection sometimes rapidly changes between multiple notes.

Web app in Safari 13.0.3. and Chrome 78.0.3904.87
User reproduced on multiple computers.

**Comment by codebykat** [comment] 2020-02-26 05:16
Electron/web only; dupe of https://github.com/Automattic/simplenote-electron/issues/1531

**Closed by codebykat** 2020-02-26 05:16 UTC
Labels: bug
