### ISSUE TITLE
Alphabetize Option Doesn't Remain in Chrome

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/Simplenote-United#58] opened 2019-08-29 21:48 UTC
Alphabetization settings are not the default after logging out and signing back in.

### Expected

Change settings to show notes alphabetized, and have that setting remain the default until changed. 

### Observed

After logging out then logging back in, the notes showed up in the Date Modified order. 

### Reproduced

I was able to reproduce this issue, as was Andy. I logged in on https://app.simplenote.com/ and set the Alphabetized option for my notes then logged out and logged back in, noting the note order reverted to the Date Modified. 

I then logged in to https://app.simplenote.com/old and changed the setting to alphabetize. After that, they were in the Alphabetized order by default even on https://app.simplenote.com/ .

Google Chrome 
Version 76.0.3809.132 (Official Build) (64-bit)
MacBook Pro

From #2304441-zen

https://app.simplenote.com/

And 

https://app.simplenote.com/old

Simplenote 1.8.0-beta1

**Comment by ChrissiePollock** [comment] 2019-08-29 21:55
Also reported on #2310422-zen

**Comment by Robertght** [comment] 2020-01-16 08:15
There is a new report in 2634783-zen but I cannot replicate it. 

Chrome 79.0.3945.117 / macOS 10.15.2

**Comment by thehenrybyrd** [comment] 2020-05-03 09:24
Another report in #2872798-zen on Chrome 81.0.4044.92. 
I was able to reproduce in Chrome 81.0.4044.129 by:
1. logging in on https://app.simplenote.com/ and setting sort to "Alphabetized"
2. logging out
3. logging back in with an incognito tab - note order had reverted to Date Modified.

**Comment by msilbers** [comment] 2020-05-08 20:55
@thehenrybyrd that is expected. the settings are not preserved across browser instances, so an incognito window will not save that a all

**Comment by msilbers** [comment] 2020-05-08 21:00
I'm closing this issue because these reports are missing some information that lead me to believe it's all the expected behavior. I checked into each ticket.

If reopening this thread, please ensure that users are not using an incognito window or clearing their cache after each use, and that no browser extensions or add-ons are in use.

**Closed by msilbers** 2020-05-08 21:00 UTC
Labels: bug
